"""
Add db.

Revision ID: 1
Revises:

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database."""
    print(f'Запуск миграции {revision}')
    # ### commands auto generated by Alembic - please adjust! ###

    print(f'Создание таблицы `orders`')
    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('total_amount', sa.Float(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', name='orderstatus'),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='public',
    )

    print(f'Создание таблицы `payments`')
    op.create_table(
        'payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column(
            'type', sa.Enum('CASH', 'ACQUIRING', name='paymenttype'), nullable=True
        ),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'PENDING', 'COMPLETED', 'REFUNDED', 'FAILED', name='paymentstatus'
            ),
            nullable=True,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['public.orders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='public',
    )
    # ### end Alembic commands ###
    print(f'Завершение миграции {revision}')


def downgrade() -> None:
    """Downgrade database."""
    print(f'Откат миграции к {down_revision}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments', schema='public')
    op.drop_table('orders', schema='public')
    # ### end Alembic commands ###
    print(f'Завершение отката миграции к {down_revision}')
